version: '3.8'

services:
  app:
    build: src/app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
    
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    expose:
      - 3306
